name: Build GameBoy ROM

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build GameBoy ROM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare build
      run: mkdir build && cmake -B build
    - name: Build GameBoy ROM
      run: cmake --build build
    - name: Upload GameBoy ROM
      uses: actions/upload-artifact@v4
      with:
        name: Game of Life GB
        path: ./build/GameOfLife.gb
        retention-days: 7
